#!/usr/bin/env bash
#
# Wire the health check to ntfy.sh push. RUN ON hetzner.
#
#   ./install-notify-ntfy.sh          # generate a topic and install the hook
#   ./install-notify-ntfy.sh --test   # send a test push using the installed hook
#
# Installs /etc/health-check/notify, which health-check.sh calls when it exits
# non-zero. See docs/runbook-health-checks.md.
#
# THE TOPIC IS THE CREDENTIAL. ntfy.sh has no accounts and no auth in this
# mode: anyone who knows the topic name can read your alerts, and anyone who
# guesses it can send you fake ones. So:
#
#   - it is generated here, on the server, from /dev/urandom
#   - it is written straight into a 0700 root file and never printed
#   - it never passes through a terminal, a transcript, or this repo
#
# To read it (on the server, in your own terminal):
#
#     sudo grep -o 'ntfy\.sh/[a-z0-9]*' /etc/health-check/notify
#
# Then subscribe in the ntfy app (Android/iOS/web) to that topic. Put a copy in
# your password manager -- it is not recoverable if the file is lost, though it
# is trivially re-generatable by re-running this with --rotate.

set -euo pipefail

MODE="${1:-}"
DIR=/etc/health-check
DST="${DIR}/notify"

log() { printf '[%s] %s\n' "$(date +%H:%M:%S)" "$*"; }

# --- test mode -------------------------------------------------------------

if [[ "${MODE}" == "--test" ]]; then
  sudo test -x "${DST}" || { echo "no hook at ${DST} -- run without --test first" >&2; exit 1; }
  log "sending a test push"
  printf 'health-check TEST on %s at %s\nThis is a test. Nothing is wrong.\n' \
    "$(hostname -s)" "$(date -Is)" | sudo "${DST}" TEST
  log "sent -- check your phone. If nothing arrives, confirm you are subscribed"
  log "to the topic: sudo grep -o 'ntfy\\.sh/[a-z0-9]*' ${DST}"
  exit 0
fi

# --- generate --------------------------------------------------------------

# Only treat an existing hook as "already done" if it is actually an ntfy hook.
# install-notify-email.sh writes the same path, so without this test a switch
# back from email would report success and silently leave email in place --
# the kind of no-op that is only discovered when an alert does not arrive.
if sudo test -x "${DST}" && sudo grep -q 'ntfy\.sh' "${DST}" 2>/dev/null \
   && [[ "${MODE}" != "--rotate" ]]; then
  log "ntfy hook already installed at ${DST}"
  log "re-run with --rotate to generate a NEW topic (you will have to resubscribe)"
  log "read the current topic with:"
  log "  sudo grep -o 'ntfy\\.sh/[a-z0-9-]*' ${DST}"
  exit 0
fi

if sudo test -x "${DST}" && ! sudo grep -q 'ntfy\.sh' "${DST}" 2>/dev/null; then
  log "replacing a different notify channel at ${DST} (email, most likely)"
fi

log "creating ${DIR}"
sudo install -d -m 700 -o root -g root "${DIR}"

# 32 chars of base36-ish. Long enough that guessing is not a threat, short
# enough to retype if you ever have to. Generated on the box; the value is
# never echoed.
log "generating topic and writing hook (the topic is not printed)"

sudo bash -c 'set -euo pipefail
topic="dotaim-hz-$(head -c 24 /dev/urandom | od -An -tx1 | tr -d " \n" | head -c 24)"
umask 077
cat > /etc/health-check/notify <<EOF
#!/bin/sh
# Health check notify hook -- pushes to ntfy.sh.
#
# Called by health-check.sh as:  notify <VERDICT>  with the report on stdin.
#
# GENERATED by scripts/install-notify-ntfy.sh. The URL below contains the
# topic, which is the only thing keeping these alerts private. Keep this file
# 0700 root and do not paste its contents anywhere.

verdict="\$1"

# FAIL gets high priority so it breaks through a silent phone; WARN does not.
# A monitor that buzzes at 3am for a disk at 82% is a monitor you mute.
case "\$verdict" in
  FAIL) prio=high ;;
  *)    prio=default ;;
esac

# Note on escaping in the generator: \$verdict and \$prio are escaped so they
# survive into the finished file and expand when the hook RUNS. The topic below
# is deliberately NOT escaped, so it expands HERE, at generation time, and the
# finished file carries a literal URL.
curl -fsS --max-time 20 \\
  -H "Title: hetzner health-check \$verdict" \\
  -H "Priority: \$prio" \\
  -H "Tags: warning" \\
  --data-binary @- \\
  "https://ntfy.sh/${topic}" >/dev/null
EOF
chmod 700 /etc/health-check/notify
chown root:root /etc/health-check/notify'

# The heredoc above expands ${topic} at generation time, so the finished file
# carries a literal URL. Confirm that happened rather than leaving a hook that
# posts to the string "${topic}".
if sudo grep -q 'ntfy\.sh/dotaim-hz-[0-9a-f]\{24\}' "${DST}"; then
  log "hook installed, topic embedded"
else
  echo "FAIL: the generated hook does not contain a valid topic URL" >&2
  echo "      inspect it: sudo cat ${DST}" >&2
  exit 1
fi

log "verifying it is executable by root only"
sudo stat -c '  %n  %a  %U:%G' "${DST}"

cat <<EOF

  NEXT, in your own terminal (the topic must not go through a transcript):

    1. Read the topic:
         sudo grep -o 'ntfy\.sh/[a-z0-9-]*' ${DST}

    2. Install the ntfy app, or open https://ntfy.sh in a browser,
       and subscribe to that topic.

    3. Save it in your password manager.

    4. Send yourself a test:
         ~/server_ops/scripts/install-notify-ntfy.sh --test

EOF
