#!/usr/bin/env bash
#
# Restore real client IPs behind Cloudflare. RUN ON hetzner.
#
#   ./install-remoteip.sh --dry-run   # generate and show the config, install nothing
#   ./install-remoteip.sh             # generate, validate, install, reload
#   ./install-remoteip.sh --refresh   # same, for when Cloudflare changes its ranges
#
# The problem this fixes: every access log on this server records the
# Cloudflare edge IP as the client. Sampled 2026-08-09 on ayatalquran.com, the
# top eight "clients" were 104.22.x / 172.64-71.x / 162.158.x -- all Cloudflare.
# Three consequences, in increasing order of how much they will cost you:
#
#   1. Abuse investigation is blind. "Which IP is hammering us" has no answer.
#   2. Any HTTP-level fail2ban jail or mod_evasive rule would ban Cloudflare,
#      taking the whole site off the internet for everyone. This is the reason
#      to fix it before adding rate limiting, not after.
#   3. .htaccess `Require ip` rules silently match the wrong thing -- they
#      either allow everyone or nobody, and both look like a broken site.
#
# The `combined` LogFormat already uses %h, and mod_remoteip rewrites %h in
# place, so no vhost and no LogFormat needs to change. Logs simply start
# carrying real IPs at the next request.
#
# Ranges are fetched from Cloudflare at install time rather than committed
# here: they change, and a stale hardcoded list fails in the worst possible
# way -- silently reverting to logging edge IPs for whichever ranges are new.
# Re-run with --refresh a couple of times a year; the daily health check does
# not police this because a stale list degrades logging, not availability.

set -euo pipefail

MODE="${1:-}"
DRY=0
[[ "${MODE}" == "--dry-run" ]] && DRY=1

DST=/etc/apache2/conf-available/remoteip-cloudflare.conf
LINK=/etc/apache2/conf-enabled/remoteip-cloudflare.conf
BAK_DIR=/var/backups/apache2
TMP=$(mktemp)
trap 'rm -f "${TMP}"' EXIT

log() { printf '[%s] %s\n' "$(date +%H:%M:%S)" "$*"; }
run() { if (( DRY )); then printf '  would: %s\n' "$*"; else "$@"; fi; }

# --- fetch ranges ----------------------------------------------------------

log "fetching Cloudflare IP ranges"
v4=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4) || {
  echo "FAIL: could not fetch ips-v4 from Cloudflare" >&2; exit 1; }
v6=$(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6) || {
  echo "FAIL: could not fetch ips-v6 from Cloudflare" >&2; exit 1; }

# Sanity-check before trusting it. A captive portal or an error page returning
# 200 would otherwise be written straight into an Apache config as a trusted
# proxy list, and `RemoteIPTrustedProxy <html>` is not a good day.
n4=$(grep -cE '^[0-9.]+/[0-9]+$' <<< "${v4}" || true)
n6=$(grep -cE '^[0-9a-fA-F:]+/[0-9]+$' <<< "${v6}" || true)
if (( n4 < 5 || n6 < 3 )); then
  echo "FAIL: fetched list does not look like CIDR ranges (v4=${n4}, v6=${n6})" >&2
  exit 1
fi
log "got ${n4} IPv4 and ${n6} IPv6 ranges"

# --- generate --------------------------------------------------------------

{
  cat <<EOF
# /etc/apache2/conf-available/remoteip-cloudflare.conf
#
# GENERATED by scripts/install-remoteip.sh on $(date -Is). Do not hand-edit --
# re-run the script with --refresh instead.
#
# Makes %h in the access logs the real visitor IP rather than the Cloudflare
# edge that relayed the request.

# CF-Connecting-IP rather than X-Forwarded-For. Cloudflare sets it to exactly
# one address, the true client, and overwrites any value the client sent. XFF
# arrives as a chain that a client can prepend to, so parsing it correctly is
# fiddly in a way that has produced real spoofing bugs elsewhere.
RemoteIPHeader CF-Connecting-IP

# The header is honoured ONLY on connections arriving from these ranges. That
# is what makes it safe: someone hitting the origin directly with a forged
# CF-Connecting-IP header is not in this list, so the header is ignored and
# %h stays their real address. Without this line the header would be a
# free-form "tell me who you are" field.
#
# Sites not behind Cloudflare are unaffected -- their connections never match
# a trusted range, so nothing is rewritten.

# IPv4
EOF
  while IFS= read -r cidr; do
    [[ -n "${cidr}" ]] && printf 'RemoteIPTrustedProxy %s\n' "${cidr}"
  done <<< "${v4}"

  printf '\n# IPv6\n'
  while IFS= read -r cidr; do
    [[ -n "${cidr}" ]] && printf 'RemoteIPTrustedProxy %s\n' "${cidr}"
  done <<< "${v6}"
} > "${TMP}"

if (( DRY )); then
  echo
  sed 's/^/    /' "${TMP}"
  echo
  log "dry run -- nothing changed"
  exit 0
fi

# --- install ---------------------------------------------------------------

if [[ -f "${DST}" ]]; then
  # Compare ignoring the generated-on line, so an unchanged range list is a
  # no-op rather than a pointless reload.
  if diff -q <(grep -v '^# GENERATED' "${DST}") <(grep -v '^# GENERATED' "${TMP}") >/dev/null; then
    log "ranges unchanged -- nothing to do"
    exit 0
  fi
  sudo mkdir -p "${BAK_DIR}"
  bak="${BAK_DIR}/remoteip-cloudflare.conf.$(date +%F-%H%M%S)"
  log "backing up existing config to ${bak}"
  sudo cp "${DST}" "${bak}"
fi

log "installing ${DST}"
sudo install -o root -g root -m 644 "${TMP}" "${DST}"

if ! apache2ctl -M 2>/dev/null | grep -q remoteip_module; then
  log "enabling mod_remoteip"
  sudo a2enmod remoteip >/dev/null
fi

log "enabling config"
sudo a2enconf remoteip-cloudflare >/dev/null

log "validating"
if ! sudo apache2ctl configtest 2>&1 | tail -1; then
  echo "FAIL: configtest failed -- disabling and leaving Apache as it was" >&2
  sudo a2disconf remoteip-cloudflare >/dev/null || true
  sudo apache2ctl configtest
  exit 1
fi

log "reloading apache (graceful -- in-flight requests finish)"
sudo systemctl reload apache2

echo
log "done. Confirm on the next request to a Cloudflare-fronted site:"
log "  tail -2 /var/www/vhosts/dotaim/ayatalquran.com/logs/access.log"
log "the leading field should no longer be a 104.x / 172.6x Cloudflare address"
echo
log "NOTE: log lines written before now still show edge IPs. Anything that"
log "      parses history (Matomo log import, abuse reports) sees a boundary"
log "      at this timestamp, not a clean rewrite of the past."
